services:
  storage:
    build:
      context: ./src
      dockerfile: ./Dockerfile.dev
    ports:
      - "82:80"
    environment:
      - FAILOVER_TOLERANCE=1

      - DIR_DISKS=/disks
      - DIR_STORAGE=/storage
      - DIR_TRASH=/trash
      - DIR_LOGS=/logs

      - AUTH_DOSSIER=a123456
      - AUTH_TEST=b123456
    volumes:
      - ./src:/var/www/html
      # Discos
      - ./disks/disk1:/disks/disk1
      - ./disks/disk2:/disks/disk2
      - ./disks/disk3:/disks/disk3
    mem_limit: 256m
    cpus: '0.25'
