services:
  storage:
    build:
      context: ./src
      dockerfile: ./Dockerfile.dev
    ports:
      - "82:80"
    environment:
      - FAILOVER_TOLERANCE=1

      - DIR_DISKS=/disks
      - DIR_STORAGE=/storage
      - DIR_TRASH=/trash
      - DIR_LOGS=/logs

      - AUTH_DOSSIER=a123456
      - AUTH_TEST=b123456
    volumes:
      - ./src:/var/www/html
      # Discos
      - ssd_disk1:/disks/ssd_disk1
      - hdd_disk2:/disks/hdd_disk2
      - hdd_disk3:/disks/hdd_disk3
      - ssd_disk4:/disks/ssd_disk4
    mem_limit: 256m
    cpus: '0.25'

volumes:
  ssd_disk1:
    driver: local
    driver_opts:
      type: none
      device: ./disks/ssd_disk1
      o: bind
  hdd_disk2:
    driver: local
    driver_opts:
      type: none
      device: ./disks/hdd_disk2
      o: bind
  hdd_disk3:
    driver: local
    driver_opts:
      type: none
      device: ./disks/hdd_disk3
      o: bind
  ssd_disk4:
    driver: local
    driver_opts:
      type: none
      device: ./disks/ssd_disk4
      o: bind
