services:
  storage:
    build:
      context: ./src
      dockerfile: ./Dockerfile.dev
    restart: always
    ports:
      - "82:80"
    environment:
      - FAILOVER_TOLERANCE=1

      - DIR_DISKS=/disks

      - AUTH_DOSSIER=a123456

      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./src:/var/www/html
      # Discos
      - ssd_disk1:/disks/ssd_disk1
      - hdd_disk2:/disks/hdd_disk2
      - hdd_disk3:/disks/hdd_disk3
      - ssd_disk4:/disks/ssd_disk4
    networks:
      - bifrost-net-storage
    mem_limit: 256m
    cpus: '0.25'

  redis:
    image: redis:alpine3.20
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_storage_data:/data
    networks:
      - bifrost-net-storage
    command: redis-server --appendonly yes # Habilita persistencia de dados

networks:
  bifrost-net-storage:

volumes:
  redis_storage_data:
    name: redis_storage_data
  ssd_disk1:
    driver: local
    driver_opts:
      type: none
      device: ./disks/ssd_disk1
      o: bind
  hdd_disk2:
    driver: local
    driver_opts:
      type: none
      device: ./disks/hdd_disk2
      o: bind
  hdd_disk3:
    driver: local
    driver_opts:
      type: none
      device: ./disks/hdd_disk3
      o: bind
  ssd_disk4:
    driver: local
    driver_opts:
      type: none
      device: ./disks/ssd_disk4
      o: bind
